alert("Bem vindo!")
let  nome=prompt("Digite o seu nome?:")
let idade=prompt("Digite A sua idade?:")
let confirmIdate=confirm(`confirma a sua idade ${idade}`)
alert(` o nome do usuario é ${nome}  \ne a sua idade é ${idade}  \na confirmação da idade é ${confirmIdate}`)